### PR TITLE
reset and migrate actions now require user confirmation

### PR DESCRIPTION
**Pull request by julienc91**
A `confirmation_required` decorator that asks the user for confirmation before calling the decorated function was added. This decorator is set on the `migrate` and `reset` actions.
Adding the `-y` or `--assume-yes` parameter on the command line allows the user to skip the confirmation input.

Solves issue #19

### CODE REVIEW

**Comment by danielkza** [comment]
The code looks pretty good! I just have one concern, about existing scripts breaking by lacking the `-y` flag. I thought about checking if `stdin` is a TTY, but that still break some weird environments (like Travis CI that emulates a terminal). Any good ideas?

**Comment by julienc91** [comment]
I added a `cli_mode` parameter on the `opts` object, set to `True` by the `main` function of `cli.py`.
The value is checked by the `confirmation_required`. If the value is `False` or not set, the confirmation is not prompted.
Do you think this is enough?

**Comment by danielkza** [comment]
@julienc91 I don't think the issue is that people are using the project as a lib, but that they call the command in automated processes (which we also do at Cobli), and they will now start to fail with a prompt.

What if instead of adding the `cli_mode` option, you set `assume_yes` to true in `cli.py` if `sys.stdin.isatty()` is `True`.

**Comment by julienc91** [comment]
@danielkza Ok, I didn't get that the first time. But I'm still not sure to understand when you say:

> What if instead of adding the cli_mode option, you set assume_yes to true in cli.py if sys.stdin.isatty() is True

You meant `False` right? Otherwise I don't understand why we would want to disable the prompt when running from a TTY? Still not sure about how it would behave on the "weird environments" you talked about [here](https://github.com/Cobliteam/cassandra-migrate/pull/21#issuecomment-333695778) though...

**Comment by danielkza** [comment]
@julienc91 Yes, I did mean `False`, sorry!

There's really not much to do about the weird envs, other than add some info on the README. I'll make sure to do that before the next release, and possibly bump to 0.3.

Thank you very much for your contribution!

**Pull request merged**
