### PR TITLE
Fix missing imports in migrator.py.

### PR DESCRIPTION
**Pull request by thomir**
A couple of small fixes:

 - Add missing imports to migrator.py
- Remove some imports that weren't used (also in migrator.py).

### CODE REVIEW

**Comment by danielkza** [comment]
Thanks for noticing! I've been putting off setting up some linting and tests, but I need to stop being lazy.

**Comment by thomir** [comment]
Is there anything preventing this from landing? It would be great to get this into master and released to pypi.

**Comment by danielkza** [comment]
Sorry I've just been a bit busy with other stuff. I'll cut out a new
release today.

Em sex, 4 de ago de 2017 00:31, Thomi Richards <notifications@github.com>
escreveu:

**Comment by danielkza** [comment]
Sorry that I took much more than I should to handle this, but it is fixed by c7502394252c4285261b74b77f7bebe82a225ab1. Such stupid errors should not happen again, since I some basic linting is enabled now.

Thanks!

**Pull request closed without merging**
